version: '3'

services:
  tdengine:
    container_name: "tdengine"
    image: tdengine/tdengine:3.0.2.5
    restart: always
    ports:
      - 6020:6020
      - 6030:6030
      - 6035:6035
      - 6030-6039:6030-6039/udp