version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq:v1.2.1
    command: /nsqd -data-path=/data --lookupd-tcp-address=nsqlookupd:4160  --broadcast-address=nsqd  # --broadcast-address=对外IP地址
    depends_on:
      - nsqlookupd
    volumes:
      - /nsqd-1-data:/data
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq:v1.2.1
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"