version: '3'

services:
  redis_no_persistent:
    container_name: "redis_no_persistent"
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379